[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/checkout/pix"
  to = "/.netlify/functions/create-pix"
  status = 200

[[redirects]]
  from = "/api/pix/status"
  to = "/.netlify/functions/pix-status"
  status = 200

[[redirects]]
  from = "/api/meta-capi/event"
  to = "/.netlify/functions/meta-capi"
  status = 200

[[redirects]]
  from = "/api/monitor/event"
  to = "/.netlify/functions/monitor-event"
  status = 200

[[redirects]]
  from = "/api/zeroonepay/webhook"
  to = "/.netlify/functions/zeroonepay-webhook"
  status = 200
