[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/checkout/pix"
  to = "/.netlify/functions/create-pix"
  status = 200

[[redirects]]
  from = "/api/pix/status"
  to = "/.netlify/functions/pix-status"
  status = 200

[[redirects]]
  from = "/api/meta-capi/event"
  to = "/.netlify/functions/meta-capi"
  status = 200

[[redirects]]
  from = "/api/monitor/event"
  to = "/.netlify/functions/monitor-event"
  status = 200

[[redirects]]
  from = "/api/ticto/webhook"
  to = "/.netlify/functions/ticto-webhook"
  status = 200

[[redirects]]
  from = "/api/appmax/webhook"
  to = "/.netlify/functions/appmax-webhook"
  status = 200

[[redirects]]
  from = "/api/appmax/health"
  to = "/.netlify/functions/appmax-health"
  status = 200

[[redirects]]
  from = "/api/infinitpay/webhook"
  to = "/.netlify/functions/infinitpay-webhook"
  status = 200

[[redirects]]
  from = "/api/mangofy/webhook"
  to = "/.netlify/functions/mangofy-webhook"
  status = 200
